/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Avatar: typeof import('./components/Avatar/index.vue')['default']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImageViewer: typeof import('element-plus/es')['ElImageViewer']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Icon: typeof import('./components/Icon/index.vue')['default']
    IconCommunity: typeof import('@/components/Icon/IconCommunity.vue')['default']
    IconDocumentation: typeof import('@/components/Icon/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('@/components/Icon/IconEcosystem.vue')['default']
    IconSupport: typeof import('@/components/Icon/IconSupport.vue')['default']
    IconTooling: typeof import('@/components/Icon/IconTooling.vue')['default']
    IEpSuccessFilled: typeof import('~icons/ep/success-filled')['default']
    LoginBox: typeof import('./components/LoginBox/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./components/TheWelcome.vue')['default']
    UserSettingBox: typeof import('./components/UserSettingBox/index.vue')['default']
    WelcomeItem: typeof import('./components/WelcomeItem.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
